locale: pt-PT
# basic options
title: Tiago Gonçalves - Projecto Genesis
author: tvieiragoncalves
email: tvieiragoncalves@gmail.com
description: In principio creavit Deus caelum et terram
twitter_username: tiago_1989
github_username:  tvieiragoncalves

# Build settings
markdown: kramdown
remote_theme: mmistakes/so-simple-theme

disqus:
  shortname: genesis-2

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-youtube

footer_links:
  - title: Twitter
    url: https://twitter.com/tiago_1989
    icon: fab fa-twitter-square
  - title: GitHub
    url: https://github.com/tvieiragoncalves
    icon: fab fa-github-square
  - title: Facebook
    url: https://mhresources.pt/
    icon: fab fa-facebook-square
  - title: Feed
    url: feed.xml
    icon: fas fa-rss-square

search_full_content: true

google_analytics: UA-28822996-1 
